Fix ruby syntax error that breaks the uninstall process.
The missing "?" causes the following error.

Error: Could not set 'absent' on ensure: undefined method `exists' for File:Class at /tmp/vagrant-puppet/modules-001663b571c9809ae1951a992dc8dd08/maldet/manifests/insta
ll.pp:33

Puppet 4.10.6 was used when testing this.